trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  kubernetesServiceConnection: 'AzureServiceConnection'

steps:
  - task: KubernetesManifest@1
    displayName: 'Apply Kubernetes manifests'
    inputs:
      action: 'deploy'
      manifests: '$(System.DefaultWorkingDirectory)/kubernetes/*.yaml'
      kubernetesServiceConnection: '$(kubernetesServiceConnection)'  
